module.exports = [
  { name: "$sudo help", type: "PLAYING" },
  { name: "GNOME Asia Summit", type: "PLAYING" },
  { name: "Community Outreach Programs", type: "LISTENING" },
  { name: "Local Meetups and Workshops", type: "WATCHING" },
  { name: "GNOME Nepal Contributions", type: "PLAYING" },
  { name: "Collaborative Projects", type: "LISTENING" },
  { name: "Volunteer Initiatives", type: "WATCHING" },
  { name: "Local GNOME Nepal Meetups", type: "PLAYING" },
  { name: "Workshops and Training", type: "LISTENING" },
  { name: "Community Outreach", type: "WATCHING" },
  { name: "International Collaboration", type: "PLAYING" },
  { name: "Events and Conferences", type: "LISTENING" },
  { name: "Local Community Engagement", type: "WATCHING" },
  { name: "GNOME Nepal Community", type: "PLAYING" },
  { name: "Open Source Contributions", type: "LISTENING" },
  { name: "Local Events and Workshops", type: "WATCHING" },
  { name: "GNOME Nepal", type: "LISTENING" },
  { name: "GNOME Nepal", type: "PLAYING" },
];
